INSERT INTO `department` (`name`) VALUES
    ('Phòng Phát triển ứng dụng web'),
    ('Phòng Quản trị cơ sở dữ liệu'),
    ('Phòng Thiết kế giao diện người dùng'),
    ('Phòng Phát triển ứng dụng di động'),
    ('Phòng Kiểm thử phần mềm'),
    ('Phòng Phân tích hệ thống'),
    ('Phòng Quản lý dự án'),
    ('Phòng Điều hành máy chủ'),
    ('Phòng An ninh thông tin'),
    ('Phòng Nghiên cứu và phát triển'),
    ('Phòng Đám mây và hệ thống phân tán'),
    ('Phòng Phát triển phần mềm nền tảng'),
    ('Phòng Kỹ thuật DevOps'),
    ('Phòng Tối ưu hóa hiệu suất'),
    ('Phòng Trí tuệ nhân tạo'),
    ('Phòng Phân tích dữ liệu'),
    ('Phòng Phát triển ứng dụng đa nền tảng'),
    ('Phòng Mạng và Bảo mật'),
    ('Phòng Quản trị hạ tầng IT'),
    ('Phòng Blockchain và Cryptocurrency');

INSERT INTO `role` (`code`, `role_title`, `role_project`, `status`) VALUES
    ('dev', 'Nhà phát triển', 'Dự án Web ABC', 1),
    ('dba', 'Quản trị cơ sở dữ liệu', 'Dự án Quản lý Khách hàng', 1),
    ('uiux', 'Thiết kế giao diện người dùng', 'Dự án App Mobile XYZ', 1),
    ('mobiledev', 'Nhà phát triển ứng dụng di động', 'Dự án E-commerce', 1),
    ('tester', 'Kỹ thuật viên kiểm thử', 'Dự án Beta Testing', 1),
    ('systemanalyst', 'Chuyên viên phân tích hệ thống', 'Dự án ERP', 1),
    ('pm', 'Quản lý dự án', 'Dự án XYZ', 1),
    ('sysadmin', 'Nhân viên quản trị máy chủ', 'Dự án Máy chủ Ảo', 1),
    ('security', 'Chuyên gia an ninh thông tin', 'Dự án Bảo mật 123', 1),
    ('rd', 'Kỹ sư nghiên cứu và phát triển', 'Dự án Nghiên cứu mới', 1),
    ('cloud', 'Chuyên gia đám mây và hệ thống phân tán', 'Dự án Đám mây ABC', 1),
    ('platformdev', 'Phát triển phần mềm nền tảng', 'Dự án Platform X', 1),
    ('devops', 'Kỹ thuật viên DevOps', 'Dự án CI/CD', 1),
    ('performance', 'Chuyên gia tối ưu hóa hiệu suất', 'Dự án Tăng tốc 123', 1),
    ('ai', 'Nhà phân tích trí tuệ nhân tạo', 'Dự án AI ABC', 1),
    ('dataanalyst', 'Chuyên viên phân tích dữ liệu', 'Dự án Big Data XYZ', 1),
    ('crossplatform', 'Nhà phát triển ứng dụng đa nền tảng', 'Dự án App Đa nền tảng', 1),
    ('network', 'Kỹ thuật viên mạng và bảo mật', 'Dự án Mạng ABC', 1),
    ('itadmin', 'Quản trị hạ tầng IT', 'Dự án Quản lý Hạ tầng', 1),
    ('blockchain', 'Chuyên gia Blockchain và Cryptocurrency', 'Dự án Blockchain XYZ', 1),
    ('designer1', 'Nhà thiết kế đồ họa', 'Dự án Thiết kế 123', 1),
    ('support1', 'Nhân viên hỗ trợ kỹ thuật', 'Dự án Hỗ trợ ABC', 1),
    ('sales1', 'Nhân viên kinh doanh', 'Dự án Kinh doanh XYZ', 1),
    ('content1', 'Chuyên gia nội dung', 'Dự án Nội dung ABC', 1),
    ('researcher1', 'Nhà nghiên cứu', 'Dự án Nghiên cứu XYZ', 1),
    ('hr1', 'Nhân viên quản lý nhân sự', 'Dự án Quản lý Nhân sự', 1),
    ('finance1', 'Nhân viên tài chính', 'Dự án Tài chính ABC', 1),
    ('legal1', 'Chuyên gia pháp lý', 'Dự án Pháp lý XYZ', 1),
    ('marketing1', 'Nhân viên marketing', 'Dự án Marketing ABC', 1),
    ('trainer1', 'Huấn luyện viên', 'Dự án Đào tạo XYZ', 1),
    ('logistics1', 'Nhân viên vận chuyển', 'Dự án Vận chuyển ABC', 1),
    ('quality1', 'Chuyên gia đảm bảo chất lượng', 'Dự án Đảm bảo chất lượng', 1),
    ('consultant1', 'Chuyên gia tư vấn', 'Dự án Tư vấn XYZ', 1),
    ('artist1', 'Nghệ sĩ đa phương tiện', 'Dự án Nghệ sĩ ABC', 1),
    ('photographer1', 'Nhiếp ảnh gia', 'Dự án Nhiếp ảnh XYZ', 1),
    ('translator1', 'Biên dịch viên', 'Dự án Biên dịch ABC', 1),
    ('architect1', 'Kiến trúc sư', 'Dự án Kiến trúc XYZ', 1),
    ('analyst1', 'Chuyên gia phân tích', 'Dự án Phân tích ABC', 1),
    ('writer1', 'Nhà văn', 'Dự án Văn học XYZ', 1),
    ('editor1', 'Biên tập viên', 'Dự án Biên tập ABC', 1),
    ('nutritionist1', 'Chuyên gia dinh dưỡng', 'Dự án Dinh dưỡng XYZ', 1),
    ('coach1', 'Huấn luyện viên thể thao', 'Dự án Huấn luyện thể thao', 1),
    ('therapist1', 'Chuyên gia tâm lý học', 'Dự án Tâm lý học ABC', 1),
    ('designer2', 'Nhà thiết kế', 'Dự án Thiết kế XYZ', 1),
    ('analyst2', 'Chuyên gia phân tích', 'Dự án Phân tích ABC', 1),
    ('developer1', 'Nhà phát triển', 'Dự án Phát triển XYZ', 1),
    ('researcher2', 'Nhà nghiên cứu', 'Dự án Nghiên cứu ABC', 1);


